import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docs: [
        "intro",
        {
            type: "category",
            label: "Operators",
            items: [
                "operators/transforming",
                "operators/batching",
                "operators/concurrency",
                "operators/sources",
            ],
        },
        "errors",
        "migrating",
        "diagrams",
        {
            type: "category",
            label: "API",
            link: { type: "doc", id: "api/index" },
            items: [{ type: "autogenerated", dirName: "api" }],
        },
    ],
};

export default sidebars;
