import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docs: [
        "intro",
        {
            type: "category",
            label: "API",
            link: { type: "doc", id: "api/index" },
            items: [{ type: "autogenerated", dirName: "api" }],
        },
    ],
};

export default sidebars;
